version: '3'
services:
  nginx:
    container_name: server
    build: ./nginx
    ports:
      - "3331:8002"
    depends_on:
      - web
    networks:
      - app-ws
    stdin_open: true
    tty: true
  database:
    container_name: db
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart_dms
      TZ: "Asia/Manila"
      PGTZ: "Asia/Manila"
    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-ws
  web:
    container_name: app
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:8002"]
      interval: 5s
      timeout: 2s
      retries: 15    
    environment:
      NODE_ENV: staging
      TZ: "Asia/Manila"
    volumes:
      - ./project:/app/
      - /app/node_modules
    networks:
      - app-ws
    stdin_open: true
    tty: true
    depends_on:
      - database
networks:
  app-ws:
    driver: bridge