apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --controller deployment --volumes persistentVolumeClaim
      --chart
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "3331"
    port: 3331
    targetPort: 3331
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
